# Generated by Django 3.0.7 on 2020-06-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_command',
            name='allowed_roles',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='custom_command',
            name='dm_response',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='custom_command',
            name='ignored_roles',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='custom_command',
            name='response',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='custom_command',
            name='response_channel',
            field=models.CharField(max_length=200),
        ),
    ]
